### ISSUE TITLE
AZ400 section 3.1 markdown table format issue

### ISSUE THREAD

**Issue by myoriginalusername** [undergroundwires/Azure-in-bullet-points#4]
https://github.com/undergroundwires/Azure-in-bullet-points/blob/master/AZ-400%20Microsoft%20Azure%20DevOps%20Solutions/3.1.%20Azure%20Boards.md#-choose-a-process

![image](https://user-images.githubusercontent.com/13319608/85206690-a0b61d80-b31b-11ea-883a-961fd000469b.png)

I'm guessing this is supposed to be a markdown table but the formatting has gone wrong and it's hard to make sense of what the table is supposed to look like. 

Maybe it's supposed to look a little more like this?
![image](https://user-images.githubusercontent.com/13319608/85206777-26d26400-b31c-11ea-9d33-a737c1c3072d.png)

**Comment by myoriginalusername** [comment]
I've created a PR for this:
https://github.com/undergroundwires/Azure-in-bullet-points/pull/5

**Comment by undergroundwires** [comment]
#5 is merged on master. Thank you for detecting & putting time into fixing this @myoriginalusername , appreciated 👍
